### ISSUE TITLE
[Request] Language System

### ISSUE THREAD

**Issue by Vulcanraven91** [wecooperate/iDefender#1]
Greetings, could you add a translation system?

I would like to translate this into German/English.
Thanks for your great software.

best regards

**Comment by wecooperate** [comment]
2.0.1 has been released and support multi-language switch,you can download the lastest version.

**Comment by luca364** [comment]
Will this be added into the 4.0 again?

**Comment by wecooperate** [comment]
The current translation is not very professional, we license it to our partners, and will launch an independent international product in the future。




---Original---
From: ***@***.***&gt;
Date: Mon, Mar 11, 2024 01:46 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [wecooperate/iDefender] [Request] Language System (Issue #1)




 
Will this be added into the 4.0 again?
