### ISSUE TITLE
规则模板内容的建议！ 还有个小问题

### ISSUE THREAD

**Issue by sanhu5** [wecooperate/iDefender#10]
1.图里面写了，希望可以优化
2.日志加一个刷新功能。有时候需要重新开关界面才能看到新的

![模板建议](https://user-images.githubusercontent.com/59349735/231744150-ebd1dae6-b17a-43b3-b3bc-c189850e415d.jpg)

小问题：
添加一个阻止加载驱动的规则，改为询问。全程没有加载驱动的弹窗，被静默阻止了，日志文字描述也不是很精准，里面写的加载模块
测试软件
[PCHunter_1.56.zip](https://github.com/wecooperate/iDefender/files/11222223/PCHunter_1.56.zip)

![1681389345656](https://user-images.githubusercontent.com/59349735/231760306-ca034b6d-2a35-4ea2-931f-399b2ed6a9e3.png)

![1681389619452](https://user-images.githubusercontent.com/59349735/231761236-a742a03b-002d-4261-a4fe-93ed321db20a.png)

**Comment by sanhu5** [comment]
> 1. 这里的事件目前是iMonitorSDK支持的原始事件，对应于系统API的接口，后面看看怎么优化成比较容易理解的事件；或者新增加一些模板来支持上面说的新建、修改、删除等容易理解事件规则。
>    （比如新建、修改、删除目前可能是相同的一个事件，需要做额外的处理才能适配；隐藏也不是直接的事件，需要额外处理才能支持）
> 2. 切换标签页的时候可以刷新，下个版本添加一个刷新按钮和F5刷新
> 3. 加载驱动这个是因为弹框的时候会判断进程路径是否存在，不存在就不弹框，加载驱动是System进程加载的，目前进程路径是空的，已经优化，下个版本发布。
>    目前的行为是具体事件的类型，因为动态库加载、驱动加载都是使用相同的一个事件类型，都是加载模块。

nice

**Comment by wecooperate** [comment]
新建你是怎么新建的？我测试通过cmd新建是可以拦截的
![image](https://user-images.githubusercontent.com/63456933/231801252-38a3b4a3-28a0-48d2-a02f-676794d33a9b.png)

**Comment by sanhu5** [comment]
> 新建你是怎么新建的？我测试通过cmd新建是可以拦截的 ![image](https://user-images.githubusercontent.com/63456933/231801252-38a3b4a3-28a0-48d2-a02f-676794d33a9b.png)

桌面右键 新建txt、改名、删除。操作者都是explorer.exe

**Comment by wecooperate** [comment]
因为匹配到目录的规则啊，是会拦截的。
新建的文件名规则匹配不到，就不会拦截。

**Comment by wecooperate** [comment]
新建一个匹配规则的文件（比如123.exe， 简单可以通过cmd来操作），是可以拦截创建的

**Comment by sanhu5** [comment]
> 因为匹配到目录的规则啊，是会拦截的。 新建的文件名规则匹配不到，就不会拦截。

我理解了。 
还是以iMonitorSDK为基准的监控，拦截比较细。不过作为主防软件一般不会这么判断。

**Comment by wecooperate** [comment]
2.6.1 发布，优化上面部分问题（问题一没法简单优化，需要后续规划一下，其他问题优化了），可以更新到新的版本

- 拦截记录添加主动刷新按钮（支持F5刷新）
- 修复内核拦截事件（比如加载驱动）只能拦截，没法弹框的问题
- 修复禁止文件修改、禁止进程修改文件没法拦截通过文件重命名的方式覆盖文件的问题
- 修复部分特殊Win7启动卡慢的问题
- 优化弹框界面
  - 文件重命名支持显示重命名后的路径
  - 设置注册表值、删除注册表值支持显示注册表值的名称

**Comment by sanhu5** [comment]
> 2.6.1 发布，优化上面部分问题（问题一没法简单优化，需要后续规划一下，其他问题优化了），可以更新到新的版本
> 
> * 拦截记录添加主动刷新按钮（支持F5刷新）
> * 修复内核拦截事件（比如加载驱动）只能拦截，没法弹框的问题
> * 修复禁止文件修改、禁止进程修改文件没法拦截通过文件重命名的方式覆盖文件的问题
> * 修复部分特殊Win7启动卡慢的问题
> * 优化弹框界面
>   
>   * 文件重命名支持显示重命名后的路径
>   * 设置注册表值、删除注册表值支持显示注册表值的名称

nice.
有没有代表磁盘根目录和路劲根目录的通配符。 例如?:\ 或者C:\Users\*\AppData\Roaming  当前目录层级

**Comment by wecooperate** [comment]
只要C:\根目录，但是不要C:\xx这样的子目录？
这个需要用正则表达式，高级模板是支持正则表达式的，可以自己添加规则。

**Comment by wecooperate** [comment]
一种简单的处理是拦截C:\*，但是针对规则再加一个信任的目标 C:\*\*

**Comment by sanhu5** [comment]
> 只要C:\根目录，但是不要C:\xx这样的子目录？ 这个需要用正则表达式，高级模板是支持正则表达式的，可以自己添加规则。


 发现智能防御会拦截注册表服务设置，但看不到被添加的值
![智能防御 服务](https://user-images.githubusercontent.com/59349735/232223803-1ba1e705-ef6e-43fe-91a2-5d492cf5e8ef.png)

这个拦截驱动，显示的system，没有显示实际发起程序PCHunter。
![加载驱动](https://user-images.githubusercontent.com/59349735/232223948-bd73544f-04e0-4341-a382-022d5aad1038.png)

**Comment by sanhu5** [comment]
> 一种简单的处理是拦截C:\*，但是针对规则再加一个信任的目标 C:\*\*

在用户或者写规则角度，这样写都是没有办法的办法。
高级模板正则表达式会的人不多

**Comment by wecooperate** [comment]
1. 添加的值目前没显示，只有值名称（因为值类型比较多，一些是二进制）
2. 驱动是内核独立线程加载的，这个事件没法从所在的线程查询到对应加载的进程是什么

**Comment by sanhu5** [comment]
> 1. 添加的值目前没显示，只有值名称（因为值类型比较多，一些是二进制）
> 2. 驱动是内核独立线程加载的，这个事件没法从所在的线程查询到对应加载的进程是什么

比如HKEY LOCAL MACHINE SYSTEM CurrentControlSet Services\kEvpxx 
kEvpxx这个项拦截不拦截都无所谓，如果是可疑程序或者木马病毒  ，服务拦截的只需要监控 lmagePath 这个的内容就行了 ，

**Comment by wecooperate** [comment]
> 

嗯，下个版本优化添加一下

**Comment by wecooperate** [comment]
![value](https://user-images.githubusercontent.com/63456933/232272664-f347bb7e-7019-4181-bebb-4cdb360ee9a6.png)

复用2.6.1版本，支持了注册表值显示，重新下载安装就可以了

**Comment by eamon-cai** [comment]
想问一下是否有交流群 或者创建个交流群的打算啊

**Comment by wecooperate** [comment]
> 

现在用户量比较少，还没有，等后面多了建个交流群

**Comment by sanhu5** [comment]
> ![value](https://user-images.githubusercontent.com/63456933/232272664-f347bb7e-7019-4181-bebb-4cdb360ee9a6.png)
> 
> 复用2.6.1版本，支持了注册表值显示，重新下载安装就可以了

nice

**Comment by sanhu5** [comment]
> > 
> 
> 现在用户量比较少，还没有，等后面多了建个交流群

信任列表什么时候加个导出

**Comment by wecooperate** [comment]
信任列表导出的目的是什么？
现在的信任列表跟规则id强绑定的，导出后没法复用。
如果是希望导出规则的时候，同时把对应规则的信任条件一起导出，后续可以一起导入，这个可以支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月21日(周五) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 规则模板内容的建议！ 还有个小问题 (Issue #10)




    
现在用户量比较少，还没有，等后面多了建个交流群
  
信任列表什么时候加个导出

**Comment by sanhu5** [comment]
> 信任列表导出的目的是什么？ 现在的信任列表跟规则id强绑定的，导出后没法复用。 如果是希望导出规则的时候，同时把对应规则的信任条件一起导出，后续可以一起导入，这个可以支持。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年4月21日(周五) 下午2:24 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [wecooperate/iDefender] 规则模板内容的建议！ 还有个小问题 (Issue #10) 现在用户量比较少，还没有，等后面多了建个交流群 信任列表什么时候加个导出 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

换一台电脑 信任规则要重新学习或者询问框添加 或者手动添加，比较麻烦

**Comment by wecooperate** [comment]
嗯，这个其实就是导出规则同时带上信任列表，下个版本支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月21日(周五) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 规则模板内容的建议！ 还有个小问题 (Issue #10)




  
信任列表导出的目的是什么？ 现在的信任列表跟规则id强绑定的，导出后没法复用。 如果是希望导出规则的时候，同时把对应规则的信任条件一起导出，后续可以一起导入，这个可以支持。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年4月21日(周五) 下午2:24 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [wecooperate/iDefender] 规则模板内容的建议！ 还有个小问题 (Issue #10) 现在用户量比较少，还没有，等后面多了建个交流群 信任列表什么时候加个导出 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
换一台电脑 信任规则要重新学习或者询问框添加 或者手动添加，比较麻烦

**Comment by wecooperate** [comment]
2.7.0 发布
1. 添加了读取、新建、删除、修改的概念
2. 导出导入规则可以支持同时导出导入对应的信任列表了
