### ISSUE TITLE
2.6.1.0在win11有问题

### ISSUE THREAD

**Issue by godwasdog** [wecooperate/iDefender#11]
win11关机后再开机，服务启动了，但是窗口前台程序没启动，触发规则没有弹窗，都是马上拦截。重启系统又可以自动启动前台程序了，只要是从关机状态开机都是不会启动。

**Comment by wecooperate** [comment]
目前的主界面是通过服务定时拉起来的，可以等待一会试试看能不能启动。下个版本添加常规的自启动方式。

临时解决：可以自己在%appdata%\Microsoft\Windows\Start Menu\Programs\Startup下面创建一个快捷方式

**Comment by sanhu5** [comment]
> 目前的主界面是通过服务定时拉起来的，可以等待一会试试看能不能启动。下个版本添加常规的自启动方式。
> 
> 临时解决：可以自己在%appdata%\Microsoft\Windows\Start Menu\Programs\Startup下面创建一个快捷方式

Windows 10 IoT 企业版 LTSC 21H2 也有类似现象。启动不够快的时候 explorer被拒绝启动，手动运行也被拒绝

**Comment by godwasdog** [comment]
> 目前的主界面是通过服务定时拉起来的，可以等待一会试试看能不能启动。下个版本添加常规的自启动方式。
> 
> 临时解决：可以自己在%appdata%\Microsoft\Windows\Start Menu\Programs\Startup下面创建一个快捷方式

等了两个小时都没有拉起来

**Comment by wecooperate** [comment]
嗯，可能某些场景获取当前用户回话令牌失败了导致启动失败，下个版本定位优化一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月20日(周四) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 2.6.1.0在win11有问题 (Issue #11)




  
目前的主界面是通过服务定时拉起来的，可以等待一会试试看能不能启动。下个版本添加常规的自启动方式。
 
临时解决：可以自己在%appdata%\Microsoft\Windows\Start Menu\Programs\Startup下面创建一个快捷方式
  
等了两个小时都没有拉起来

**Comment by wecooperate** [comment]
2.7.0 发布，已经修复，请更新到新的版本
