### ISSUE TITLE
主防构架的建议！

### ISSUE THREAD

**Issue by sanhu5** [wecooperate/iDefender#12]
目前iDefender规则编辑可以添加多个程序，也可以添加多个目标，还有规则优先级，这个还是比较好的，就是粗犷了一点。
iDefender大致的流程，程序-动作-目标，不论是新建进程还是某个文件操作，勾选了以后就是对*操作，后面就没有细节了。
（如图1）
![1](https://user-images.githubusercontent.com/59349735/233103838-3778547d-4a29-4dea-b403-595b0fc0b3e5.png)

下面的当然也仅仅是建议而已，提供一个方向！
希望可以把现在的**信任列表**功能增强，名字无所谓。
主要是功能就是**程序规则管理**+**程序误报排除**。
（如图2）
![2](https://user-images.githubusercontent.com/59349735/233103858-c05eda96-3b76-4d7e-91fc-3a3863a6d1af.png)

程序-进程标签（多目标）文件标签（多目标）或 注册表标签（多目标） 里面的每一项都可以进行单独的选择编辑， 可以改为询问、阻止、允许、结束。
询问框记录的规则也是添加到这个里面来的。

**Comment by wecooperate** [comment]
很好的建议，十分感谢。我们看看怎么优化一下流程交互。

**Comment by sanhu5** [comment]
> 很好的建议，十分感谢。我们看看怎么优化一下流程交互。

我收集了些其他软件的图，你可以参考下。
![自动处理参考1](https://user-images.githubusercontent.com/59349735/233127350-bd5e240b-63aa-4e40-9578-9b30b4ac960a.png)
![自动处理参考2](https://user-images.githubusercontent.com/59349735/233127377-a53acffd-8f01-4934-96d5-e23fb4e89769.jpg)
![自动处理参考3](https://user-images.githubusercontent.com/59349735/233127391-44fac5d4-22a8-407f-af96-c787caf0cac2.jpg)
![应用程序参考](https://user-images.githubusercontent.com/59349735/233127465-9252b51e-64d4-4eb5-8e3c-ce1f6476049e.png)
![应用程序参考2](https://user-images.githubusercontent.com/59349735/233127494-7c2af596-5af3-40df-bc43-37930b194e8a.png)
![应用程序参考3](https://user-images.githubusercontent.com/59349735/233127517-6759875f-5bae-43d6-876c-adf852a20e09.png)
![应用程序参考4](https://user-images.githubusercontent.com/59349735/233127541-549f0197-ebef-4d41-b499-79e62b887396.png)

**Comment by wecooperate** [comment]
冰盾的设计跟其他软件有一些本质的差别：冰盾是完全基于模板 + 参数的规则引擎的。目的是可以只要简单的参数就可以实现需要的防护效果，而功能的扩展通过添加模板就可以实现了。一方面可能保证灵活，但是某些程度也限制了一些设计。

2.7.0 发布，添加了几个模板，用于支持读取、新建、删除、修改等模式。可以更新到新的版本体验。
![image](https://github.com/wecooperate/iDefender/assets/63456933/278525cb-d466-43f2-a981-237a2556e5c1)
