### ISSUE TITLE
对于添加信任列表的疑惑

### ISSUE THREAD

**Issue by liangxyz** [wecooperate/iDefender#13]
如题，在某些弹窗中，我对于如何添加信任列表有疑惑，比如下图中，如果我添加了永久信任该操作，软件是否会记住命令行？
<img width="661" alt="搜狗截图20230413210736" src="https://user-images.githubusercontent.com/8108927/234827169-269e66ba-1a14-4e7b-8060-b49fc014950e.png">
我就怕软件信任不带命令行，会导致直接放行所有该程序的操作，这样会出现严重安全漏洞

**Comment by wecooperate** [comment]
目前的信任列表只支持进程路径、目标路径，**不支持命令行**

**Comment by wecooperate** [comment]
对于这个规则，进程启动本身wow64进程的，下个版本优化去掉这个误报

**Comment by wecooperate** [comment]
2.7.0发布，修复了误报问题
