### ISSUE TITLE
添加了对应的信任规则但是仍然弹窗

### ISSUE THREAD

**Issue by Swizzzer** [wecooperate/iDefender#16]
[Attachment.zip](https://github.com/wecooperate/iDefender/files/11682087/Attachment.zip)
我在对应规则的信任列表中添加了相应程序，但是iDefender并未信任成功，依然会反复弹窗。

使用的规则和截图见附件。

**Comment by wecooperate** [comment]
BUG原因：多条规则的匹配缓存错误导致的，下个版本修复，感谢反馈。
过程：操作文件事件匹配到两个规则：系统文件保护、可执行文件保护，匹配到系统文件保护的时候，是返回信任的；这时候会继续匹配下个规则（可执行文件保护），因为信任缓存存在问题，导致返回了错误的结果。

**Comment by wecooperate** [comment]
临时解决：可以把everything添加到全局进程白名单里面，全局信任后就不会继续匹配其他规则了

**Comment by wecooperate** [comment]
2.8.0 发布，上面的问题修复了
