### ISSUE TITLE
目前软件是否不支持拦截通过IOCTL_SCSI_PASS_THROUGH_DIRECT对磁盘的写入/破坏

### ISSUE THREAD

**Issue by Swizzzer** [wecooperate/iDefender#17]
冰盾默认的保护选项里是支持对MBR的保护的，但是使用 https://bbs.kafan.cn/thread-2256991-1-1.html 这里的样本测试发现拦截失败。请问冰盾目前是否不支持对IOCTL_SCSI_PASS_THROUGH_DIRECT写磁盘的拦截？日后是否考虑加入相关拦截功能？

**Comment by wecooperate** [comment]
冰盾目前拦截策略是基于打开句柄的时候判断权限的，不是拦截具体的IOCTL。
现在的MBR的拦截了直接操作磁盘的（对应是\\Device\\Harddisk?\\DR?）。
IOCTL_SCSI_PASS_THROUGH_DIRECT的拦截可以自己添加一个拦截直接打开卷的规则试试：
拦截修改文件规则，文件路径为是 ?:

**Comment by Swizzzer** [comment]
添加了拦截直接打开卷的规则，但是并没有效果...
录屏文件展示了失败过程。
[bandicam 2023-06-14 12-33-52-330.zip](https://github.com/wecooperate/iDefender/files/11741636/bandicam.2023-06-14.12-33-52-330.zip)

**Comment by wecooperate** [comment]
这个是通过直接操作磁盘的，通过设置规则\Device\Harddisk?\DR? 正常是可以拦截的。
因为拦截这个误报比较多，之前安全加固里面的规则修改成WriteFile了。这个后面优化一下，你先手动添加\Device\Harddisk?\DR? 的文件拦截规则
![image](https://github.com/wecooperate/iDefender/assets/63456933/c622da8b-8904-4322-96eb-03bcf18d0789)

**Comment by wecooperate** [comment]
已经修改支持，如果是旧的版本可以更新到最新版本，如果是已经是最新的版本了，等待模块升级自动更新（锁屏的时候会下发模块更新）
![](https://github.com/wecooperate/iDefender/assets/63456933/cfa2128c-e514-4029-ba07-41c16e2a6a91)

或者自己手动添加规则也可以
