### ISSUE TITLE
驱动拦截

### ISSUE THREAD

**Issue by eamon-cai** [wecooperate/iDefender#18]
在其他类似软件中看到除了拦截 放行  还可以实现模拟加载成功，不知道现有情况是否可以实现

**Comment by wecooperate** [comment]
拦截驱动一般是驱动加载后，在驱动的入口返回失败了。也是可以直接返回加载成功的。
一般不会有这样的需求，看为啥需要这样。

**Comment by wecooperate** [comment]
现在有微信群了，欢迎通过关于页面扫码加入微信群沟通，可以方便一点。
