### ISSUE TITLE
蓝屏 - DRIVER_IRQL_NOT_LESS_OR_EQUAL

### ISSUE THREAD

**Issue by cEvolve05** [wecooperate/iDefender#19]
Microsoft Windows 11 Pro 10.0.22621 Build 22621
冰盾 2.9.1.0
dmp 文件：[071723-13515-01.zip](https://github.com/wecooperate/iDefender/files/12067121/071723-13515-01.zip)
由 iMonitor64.sys 引起
同时安装了火绒

当时正在玩游戏，突然就蓝屏了…

**Comment by wecooperate** [comment]
感谢反馈，下个版本修复

**Comment by wecooperate** [comment]
2.9.2 版本修复
