### ISSUE TITLE
规则模板

### ISSUE THREAD

**Issue by eamon-cai** [wecooperate/iDefender#2]
规则模板里面的规则编译可以考虑添加一下反选吗      有的情况下需要全局排除几个进程

**Comment by wecooperate** [comment]
信任列表（白名单）？计划中，下个版本或者下下个版本支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月28日(周三) 晚上6:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 规则模板 (Issue #2)




 
规则模板里面的规则编译可以考虑添加一下反选吗      有的情况下需要全局排除几个进程

**Comment by eamon-cai** [comment]
是的 
![QQ截图20221228205514](https://user-images.githubusercontent.com/30527166/209815659-a312c2bc-9966-45ed-bba5-7d9fa45f4e3d.png)
类似这种

**Comment by wecooperate** [comment]
白名单模式已经添加，同时添加了更多场景的规则模板，看是否满足你的需求。

**Comment by eamon-cai** [comment]
辛苦 已在使用中

**Comment by eamon-cai** [comment]
问题
只读文件监控严重影响流畅度 
icmp协议无法拦截
ipv6无法拦截
建议
网络地址增加域名支持
网络模板进程地址共同编辑 例如 禁止某某进程访问 aaa.com bbb.com  a.b.c.d

**Comment by wecooperate** [comment]
1. icmp，ipv6因为驱动未支持，需要等驱动下个版本支持后才会启动支持。
2. 只读文件监控的性能跟系统，规则等有关系。每个事件大概是0.01ms到0.1ms消耗。未来这里会考虑把规则直接设置到内核，这样对性能影响会少很多。
3.网络地址支持域名、上网行为管理（拦截http请求）正在开发中。
禁止进程访问某些网络规则模板下个版本添加。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月10日(周二) 凌晨2:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 规则模板 (Issue #2)




 
问题
 只读文件监控严重影响流畅度
 icmp协议无法拦截
 ipv6无法拦截
 建议
 网络地址增加域名支持
 网络模板进程地址共同编辑 例如 禁止某某进程访问 aaa.com bbb.com  a.b.c.d

**Comment by wecooperate** [comment]
> 问题 只读文件监控严重影响流畅度 icmp协议无法拦截 ipv6无法拦截 建议 网络地址增加域名支持 网络模板进程地址共同编辑 例如 禁止某某进程访问 aaa.com bbb.com a.b.c.d

2.3.0 版本已经发布，可以更新到新的版本体验

- 添加IPv6、ICMP拦截支持
- 网络拦截规则添加域名支持
- 添加上网行为管理（HTTP拦截）支持
- 添加HTTP请求自定义响应结果支持
- 添加规则分享支持
- 添加规则市场支持，可以通过规则市场直接下载其他人分享的规则
- 添加自保护功能
- 添加家长控制（密码保护）功能

**Comment by eamon-cai** [comment]
辛苦了 已在体验

**Comment by QQ2017** [comment]
> > 问题 只读文件监控严重影响流畅度 icmp协议无法拦截 ipv6无法拦截 建议 网络地址增加域名支持 网络模板进程地址共同编辑 例如 禁止某某进程访问 aaa.com bbb.com a.b.c.d
> 
> 2.3.0 版本已经发布，可以更新到新的版本体验
> 
> * 添加IPv6、ICMP拦截支持
> * 网络拦截规则添加域名支持
> * 添加上网行为管理（HTTP拦截）支持
> * 添加HTTP请求自定义响应结果支持
> * 添加规则分享支持
> * 添加规则市场支持，可以通过规则市场直接下载其他人分享的规则
> * 添加自保护功能
> * 添加家长控制（密码保护）功能
> * 添加更多的规则模板

现在还有文件、注册表监控的性能问题吗？

**Comment by wecooperate** [comment]
> > > 问题 只读文件监控严重影响流畅度 icmp协议无法拦截 ipv6无法拦截 建议 网络地址增加域名支持 网络模板进程地址共同编辑 例如 禁止某某进程访问 aaa.com bbb.com a.b.c.d
> > 
> > 
> > 2.3.0 版本已经发布，可以更新到新的版本体验
> > 
> > * 添加IPv6、ICMP拦截支持
> > * 网络拦截规则添加域名支持
> > * 添加上网行为管理（HTTP拦截）支持
> > * 添加HTTP请求自定义响应结果支持
> > * 添加规则分享支持
> > * 添加规则市场支持，可以通过规则市场直接下载其他人分享的规则
> > * 添加自保护功能
> > * 添加家长控制（密码保护）功能
> > * 添加更多的规则模板
> 
> 现在还有文件、注册表监控的性能问题吗？

文件、注册表监控不会存在性能问题的。
只读文件监控在某一些性能比较差、或者存在大量文件短时间读写、或者同时存在其他监控软件时有可能会出现性能问题。（我几个开发机器长期开启中，因为性能比较好，没有出现过性能问题。）

**Comment by wsyh-He** [comment]
规则后期是否可以添加导出导入功能？ 规则市场里的规则如果能添加类似ID字段，当市场里的规则多的时候直接搜索ID定位规则，这样换电脑重新安装软件搜索规则下载就方便很多。

**Comment by wecooperate** [comment]
> 

后面会添加导入导出功能。（稍微慢一点，目前正在添加端口防火墙、拦截弹框交互、信任管理等功能）

**Comment by wecooperate** [comment]
> 

2.4.0 版本发布，支持导入、导出功能。

更多说明参考 https://imonitorsdk.com/idefender#2400

**Comment by eamon-cai** [comment]
已在体验  感谢

**Comment by eamon-cai** [comment]
建议可以在拦截记录里添加快捷编辑规则方式  例如双击弹出新建规则 或者信任规则   ，或者复制功能

**Comment by wecooperate** [comment]
> 建议可以在拦截记录里添加快捷编辑规则方式 例如双击弹出新建规则 或者信任规则 ，或者复制功能

![image](https://user-images.githubusercontent.com/63456933/221175235-5ca3a897-f6bd-4e11-aa38-cc15b3a1269c.png)

大概这样，等待下个版本发布

**Comment by eamon-cai** [comment]
发现会偶发自动关闭防御 不知道和什么东西冲突 没有详细日志所以暂时没办法复现

**Comment by wecooperate** [comment]
这个问题已经知道修复了，不到流程临时发布了版本但是没有更新版本号，可以重新下载新的版本覆盖安装试试。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 凌晨0:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 规则模板 (Issue #2)




 
发现会偶发自动关闭防御 不知道和什么东西冲突 没有详细日志所以暂时没办法复现

**Comment by eamon-cai** [comment]
是最新的2.4.1.0  出现的次数非常少

**Comment by eamon-cai** [comment]
目前发现应该是和vmware冲突 开关机过程中会大概率自动关闭 vmware-vmx.exe占用会突然升高

**Comment by wecooperate** [comment]
> 

2.4.1 有两个版本的，因为是临时修复，不到更新版本的流程就复用了版本号，可以观察更新覆盖安装后是否还出现。

**Comment by wecooperate** [comment]
> 建议可以在拦截记录里添加快捷编辑规则方式 例如双击弹出新建规则 或者信任规则 ，或者复制功能

2.5.0 已经发布（拦截记录支持右键菜单、双击编辑规则）
