### ISSUE TITLE
蓝屏 - DRIVER_VERIFIER_DETECTED_VIOLATION

### ISSUE THREAD

**Issue by cEvolve05** [wecooperate/iDefender#20]
Microsoft Windows 11 Pro 10.0.22621 Build 22621
冰盾 2.9.1.0
dmp 文件：[071723-12515-01.zip](https://github.com/wecooperate/iDefender/files/12067171/071723-12515-01.zip)
由 iMonitor64.sys 引起

1. Win + R运行verifier
2. 在 “驱动程序验证程序管理器”中，选择“ 显示有关当前已验证的驱动程序的信息”，添加 iMonitor64.sys ，系统会卡住，然后蓝屏

尝试三次均可复现

**Comment by wecooperate** [comment]
目前驱动没有完全兼容verifier模式，请关闭verifier后再看看是否蓝屏。（内存分配选项是支持，其他选项没有兼容）

**Comment by wecooperate** [comment]
下个版本优化

**Comment by wecooperate** [comment]
2.9.2 版本修复
