### ISSUE TITLE
关于联网控制的疑惑？

### ISSUE THREAD

**Issue by liangxyz** [wecooperate/iDefender#21]
如题，我想自己控制是否允许进程联网，对于未知的程序，弹窗提示是否允许联网。
我把自带的禁止进程联网规则改成了弹框（默认拦截）。但是我发现打开程序以后，并不会出现联网弹窗
请问是我哪里设置不正确吗？

**Comment by wecooperate** [comment]
自带的禁止进程联网是没有规则的，需要自己把需要拦截的进程规则添加进去。
如果是调整成弹框模式，可以在进程路径里面添加一个 * 的规则，表示所有进程都拦截弹框。

 
发件人： liangxyz
发送时间： 2023-08-02 22:23
收件人： wecooperate/iDefender
抄送： Subscribed
主题： [wecooperate/iDefender] 关于联网控制的疑惑？ (Issue #21)
如题，我想自己控制是否允许进程联网，对于未知的程序，弹窗提示是否允许联网。
我把自带的禁止进程联网规则改成了弹框（默认拦截）。但是我发现打开程序以后，并不会出现联网弹窗
请问是我哪里设置不正确吗？
―

**Comment by liangxyz** [comment]
> 

谢谢，我尝试过在进程名里添加一个 * 的规则，但是不起作用没有弹窗，我回去试试在进程路径里添加

**Comment by wecooperate** [comment]
进程名不支持通配符，需要进程路径里面设置。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月3日(周四) 凌晨0:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 关于联网控制的疑惑？ (Issue #21)




   
谢谢，我尝试过在进程名里添加一个 * 的规则，但是不起作用没有弹窗，我回去试试在进程路径里添加
