### ISSUE TITLE
希望加入程序、文件、注册表等组

### ISSUE THREAD

**Issue by sanhu5** [wecooperate/iDefender#22]
既然这里可以用文件路径、文件名称、拓展名归纳，为什么不能加入组管理。
编辑的时候直接添加已有的组，可以更方便的统一调度

![1691422802595](https://github.com/wecooperate/iDefender/assets/59349735/587486d5-3a75-43a5-b1ef-1f9aff675190)

还有目前的模板太多了，有一些可以简化。
比如快速模板有信任和拦截模式，个人感觉信任模式直接编辑规则的时候直接添加信任还挺方便的，可以合二为一。
或者融合到修改文件模板去

**Comment by wecooperate** [comment]
组的概念一开始就有的，因为一方面复杂度会比较高，另外有一些细节没有考虑好，就屏蔽掉了。比如分享规则的时候，是要把组一起分享还是只是拷贝，规则导出导入时组需要怎么处理。
未来的版本会添加支持的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月7日(周一) 晚上11:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 希望加入程序、文件、注册表等组 (Issue #22)




 
既然这里可以用文件路径、文件名称、拓展名归纳，为什么不能加入组管理。
 编辑的时候直接添加已有的组，可以统一调度

**Comment by sanhu5** [comment]
> 组的概念一开始就有的，因为一方面复杂度会比较高，另外有一些细节没有考虑好，就屏蔽掉了。比如分享规则的时候，是要把组一起分享还是只是拷贝，规则导出导入时组需要怎么处理。 未来的版本会添加支持的。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月7日(周一) 晚上11:43 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [wecooperate/iDefender] 希望加入程序、文件、注册表等组 (Issue #22) 既然这里可以用文件路径、文件名称、拓展名归纳，为什么不能加入组管理。 编辑的时候直接添加已有的组，可以统一调度 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的，期待

**Comment by wecooperate** [comment]
3.0.0 版本已经支持
