### ISSUE TITLE
疑似规则缓存BUG

### ISSUE THREAD

**Issue by sanhu5** [wecooperate/iDefender#23]
一条命令行规则，我已经修改过了，理论上排除了误报。下面的程序在开机启动的时候还是会弹窗。
但是跟现有的规则好像都无法匹配上。从详细日志点进去，弹出来的规则列表是还未修改之前的规则。

C:\Users\Administrator\Desktop\Clash.for.Windows-0.20.6-win\Clash for Windows.exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=zh-CN --service-sandbox-type=none --user-data-dir="C:\Users\Administrator\AppData\Roaming\clash_win" --mojo-platform-channel-handle=2008 --field-trial-handle=1712,i,18375474046678382013,16877751175214156194,131072 --disable-features=OutOfBlinkCors,SpareRendererForSitePerProcess,WinRetrieveSuggestionsOnlyOnDemand /prefetch:8

![1692097418161](https://github.com/wecooperate/iDefender/assets/59349735/f97514bd-4439-4199-8cbc-c0fa7c24073e)

**Comment by wecooperate** [comment]
规则允许同名，存在多份规则导致
