### ISSUE TITLE
功能问题

### ISSUE THREAD

**Issue by e1yB9vz4dvR** [wecooperate/iDefender#24]
请问有拦截 键盘记录、截屏、录屏、剪切板读取 这些功能吗？
我没找到有，后面考虑加上吗？

**Comment by wecooperate** [comment]
目前没有这些功能，未来会添加但是不会那么快。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月27日(周日) 下午2:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 功能问题 (Issue #24)




 
请问有拦截 键盘记录、截屏、录屏、剪切板读取 这些功能吗？
 我没找到有，后面考虑加上吗？
