### ISSUE TITLE
软件很棒，但是有个建议！

### ISSUE THREAD

**Issue by chennqqi** [wecooperate/iDefender#26]
非开源项目别在github上打广告

**Comment by wecooperate** [comment]
开始一直是开源的，有需要可以看历史记录。但是有了很多这样的伸手党，不贡献还各种jjww就关闭开源了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月1日(周五) 上午9:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 软件很棒，但是有个建议！ (Issue #26)




 
非开源项目别在github上打广告

**Comment by chennqqi** [comment]
看了记录，确实一开始开源的。支持老哥继续开源~
