### ISSUE TITLE
运行约1天以上会蓝屏

### ISSUE THREAD

**Issue by xxhhlk** [wecooperate/iDefender#27]
如题，装冰盾之前没出现过这种情况，系统版本Win10 Pro 22H2 19045.3758，冰盾版本 3.5.0.0
问题应该可以稳定复现，之前出现过几次，没保存dmp，最近这3次保存了：链接: https://caiyun.139.com/m/i?135Cmj56YeIxT 提取码:MoVd

**Comment by wecooperate** [comment]
这个蓝屏比较奇怪 （xray.exe 监听到远程连接的数据包的时候，被冰盾挂起重新插入后，释放内存进入NETIO!NetioDereferenceNetBufferList 发生蓝屏） 功能是网络端口防火墙引起的，可以临时关闭端口防火墙规则或者关闭网络防御。具体原因需要再分析。

你也可以尝试关闭xray.exe再观察看是否还会出现？（如果不出现帮忙把蓝屏时候的xray的命令发一下，我们模拟环境看能不能重现，之前测试运行超过一个星期也不会有异常的。）

**Comment by wecooperate** [comment]
这个蓝屏比较奇怪 （xray.exe 监听到远程连接的数据包的时候，被冰盾挂起重新插入后，释放内存进入NETIO!NetioDereferenceNetBufferList 发生蓝屏） 功能是网络端口防火墙引起的，可以临时关闭端口防火墙规则或者关闭网络防御。具体原因需要再分析。

你也可以尝试关闭xray.exe再观察看是否还会出现？（如果不出现帮忙把蓝屏时候的xray的命令发一下，我们模拟环境看能不能重现，之前测试运行超过一个星期也不会有异常的。）

**Comment by xxhhlk** [comment]
谢谢 我先观察一下

**Comment by xxhhlk** [comment]
你好，对xray压测可以较快复现蓝屏，所以我做了一下测试，发现应该不是冰盾本身的锅（因为全新系统下测试正常）。还发现不开xray也会蓝屏，可以再帮我看看吗？或者说我重装系统比较好？
链接:https://caiyun.139.com/m/i?135Cm3NojwZB6
提取码:UDfH

**Comment by wecooperate** [comment]
构造了几个场景都没有复现，所以不太好确定具体的问题。
针对蓝屏的原因，下个版本会做一些优化，有可能可以修复这个原因。临时可以先通过关闭端口防火墙（或者网络防御）看是否不会再复现。

**Comment by xxhhlk** [comment]
> 构造了几个场景都没有复现，所以不太好确定具体的问题。 针对蓝屏的原因，下个版本会做一些优化，有可能可以修复这个原因。临时可以先通过关闭端口防火墙（或者网络防御）看是否不会再复现。

忘记说了，关闭网络防御确实不会蓝屏了。那么下个版本大概什么时候会发布呢？

**Comment by wecooperate** [comment]
下个版本估计会比较久了，要加个内核规则引擎，会测试比较久。目前还没有具体的计划。

另外发现电脑安装了其他类似的驱动，比如\system32\drivers\netfilter2.sys 和 system32\drivers\xlwfp.sys，可以尝试屏蔽测试看看是不是冲突导致的。

**Comment by xxhhlk** [comment]
好吧……
这俩驱动前两天测试的时候就删了，症状还是一样

**Comment by xxhhlk** [comment]
好的 谢谢 已发送
