### ISSUE TITLE
注册表部分参数失效

### ISSUE THREAD

**Issue by sanhu5** [wecooperate/iDefender#28]
![1705582906279](https://github.com/wecooperate/iDefender/assets/59349735/fd39ddbc-22f8-4461-9267-d3b873517108)
![1705582928729](https://github.com/wecooperate/iDefender/assets/59349735/038bef38-93d8-4a97-9cdc-0fd9d36de72e)

之前以为是部分模板失效了。然后测试了几次，感觉应该是路劲参数代\*的失效。
键值组合正常拦截没问题，但加\*后也失效。
比如这样写*\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\Folder\SuperHidden|*

**Comment by wecooperate** [comment]
![fbaf3a1158460816d14e63878076119](https://github.com/wecooperate/iDefender/assets/63456933/d5ca3e15-1b17-4aef-8da0-2e93b249101f)
HEKY_CLASS_ROOT因为是软链接，实际路径是HKEY_LOCAL_MACHINE\SOFTWARE\Classes，所以会失败，可以把路径换一下。

**Comment by sanhu5** [comment]
OK 改下路劲应该没问题
