### ISSUE TITLE
希望添加游戏模式

### ISSUE THREAD

**Issue by Fadouse** [wecooperate/iDefender#29]
希望添加游戏模式。
在全屏时，希望不要跳出询问窗口。

**Comment by wecooperate** [comment]
下个版本添加支持



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月4日(周日) 中午1:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 希望添加游戏模式 (Issue #29)




 
希望添加游戏模式。
 在全屏时，希望不要跳出询问窗口。

**Comment by wecooperate** [comment]
已经支持，可以托盘自己切换到静默模式（这个模式下不会弹窗）
