### ISSUE TITLE
增加命令行导入规则功能

### ISSUE THREAD

**Issue by QQ2017** [wecooperate/iDefender#3]
建议增加命令行导入、更新规则功能。

**Comment by wecooperate** [comment]
现在的规则共享可以通过分享规则后，在规则市场下载。
后续在规则列表界面会添加规则的导出、导入支持。但是不一定会支持命令行的方式。
如果有需求需要通过命令行来操作，麻烦描述一下场景，是通用需求的话会添加支持。

**Comment by QQ2017** [comment]
> 现在的规则共享可以通过分享规则后，在规则市场下载。 后续在规则列表界面会添加规则的导出、导入支持。但是不一定会支持命令行的方式。 如果有需求需要通过命令行来操作，麻烦描述一下场景，是通用需求的话会添加支持。

场景1：网吧无盘环境下，系统都是还原状态，需要通过命令行开机自动导入规则；
场景2：企业办公环境下，通过命令行导入、更新规则，可以实现终端规则批量管理。

**Comment by wecooperate** [comment]
> > 现在的规则共享可以通过分享规则后，在规则市场下载。 后续在规则列表界面会添加规则的导出、导入支持。但是不一定会支持命令行的方式。 如果有需求需要通过命令行来操作，麻烦描述一下场景，是通用需求的话会添加支持。
> 
> 场景1：网吧无盘环境下，系统都是还原状态，需要通过命令行开机自动导入规则； 场景2：企业办公环境下，通过命令行导入、更新规则，可以实现终端规则批量管理。

未来会添加统一管理的方式，可以根据不同分组设置不同的策略然后下发到终端

**Comment by wecooperate** [comment]
2.4.0 版本发布了，支持导入、导出功能。

更多说明参考 https://imonitorsdk.com/idefender#2400
