### ISSUE TITLE
4.0.1.0 卡巴斯基报毒

### ISSUE THREAD

**Issue by Fadouse** [wecooperate/iDefender#30]
Event: Malicious object detected
User: LAPTOP\Fadouse
User type: Initiator
Application name: chrome.exe
Application path: C:\Program Files\Google\Chrome\Application
Component: File Anti-Virus
Result description: Detected
Type: Trojan
Name: HEUR:Trojan.Win32.Alien.gen
Precision: Heuristic Analysis
Threat level: High
Object type: File
Object name: iDefender(4.0.1).exe
Object path: C:\Users\ASUS\Downloads
MD5 of an object: 8C3E51A24CAC6DEF434AA0CDD8D0CE81
Reason: Machine learning
Databases release date: Today, 3/10/2024 7:56:00 AM

**Comment by wecooperate** [comment]
信任了就好了。或者去卡巴那边反馈一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 上午10:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 4.0.1.0 卡巴斯基报毒 (Issue #30)




 
Event: Malicious object detected
 User: LAPTOP\Fadouse
 User type: Initiator
 Application name: chrome.exe
 Application path: C:\Program Files\Google\Chrome\Application
 Component: File Anti-Virus
 Result description: Detected
 Type: Trojan
 Name: HEUR:Trojan.Win32.Alien.gen
 Precision: Heuristic Analysis
 Threat level: High
 Object type: File
 Object name: iDefender(4.0.1).exe
 Object path: C:\Users\ASUS\Downloads
 MD5 of an object: 8C3E51A24CAC6DEF434AA0CDD8D0CE81
 Reason: Machine learning
 Databases release date: Today, 3/10/2024 7:56:00 AM
