### ISSUE TITLE
使用高级模板（内核模式）创建规则时勾选多个事件在规则条件里面只显示一个事件特有的，不显示其他的

### ISSUE THREAD

**Issue by UserNameiiiii** [wecooperate/iDefender#31]
![QQ截图20240505100544](https://github.com/wecooperate/iDefender/assets/154041370/99747c01-4147-476a-a0f5-278d578b8be7)

**Comment by wecooperate** [comment]
设计上就是这样的：选择多个事件的时候，**只会显示所有事件共同的字段**，因为不是共同字段设置了会导致其他事件匹配失败。

**Comment by UserNameiiiii** [comment]
也就是说，要多个类型分开还给创建多个规则

**Comment by wecooperate** [comment]
看具体需要，如果参数只用到了公共的事件，是不需要分开的。
比如所有文件事件里面，只用到了操作进程 + 路径，那么是可以放一起的，但是如果用到了某个事件专有的字段，需要单独一条。
