### ISSUE TITLE
请教日志在哪清，首页 运行天数这些

### ISSUE THREAD

**Issue by ddatsh** [wecooperate/iDefender#33]
如题

**Comment by wecooperate** [comment]
拦截记录可以在界面里面清理，运行日志和运行天数等不支持清理的。



---原始邮件---
发件人: "peter ***@***.***&gt;
发送时间: 2024年5月27日(周一) 上午10:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 请教日志在哪清，首页 运行天数这些 (Issue #33)




 
如题

**Comment by ddatsh** [comment]
> 拦截记录可以在界面里面清理，运行日志和运行天数等不支持清理的。
> […](#)
> ---原始邮件--- 发件人: "peter ***@***.***&gt; 发送时间: 2024年5月27日(周一) 上午10:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [wecooperate/iDefender] 请教日志在哪清，首页 运行天数这些 (Issue #33) 如题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

这个被定义为敏感信息了吗？ 没存在什么文件/db/注册表 里可以删了清吗.. 强迫症啊
