### ISSUE TITLE
无法拦截通过Direct System Call执行的进程注入行为

### ISSUE THREAD

**Issue by Swizzzer** [wecooperate/iDefender#34]
## 描述

开启增强防御后，使用[https://bbs.kafan.cn/thread-2272539-1-1.html](url)中的样本测试。确认样本执行成功，但iDefender无任何注入拦截提示。

## 系统环境

版本    Windows 10 专业版
版本号    22H2
安装日期    ‎2024/‎3/‎31
操作系统内部版本    19045.4780
体验    Windows Feature Experience Pack 1000.19060.1000.0

## 复现步骤

1. 开启所有默认规则
2. 开启增强防御
3. 导入自制规则[myrule.zip](https://github.com/user-attachments/files/16673247/myrule.zip)
4. 在规则制定的文件夹下运行样本

## 预期结果

参考IDA逆向结果和云沙箱结果，该样本会通过Direct Syscall ZwCreateThreadEx函数，最终注入explorer.exe，在这个过程中应提示拦截。

**Comment by wecooperate** [comment]
开启默认都资源管理器防御了吗？
这个使用进程保护来拦截。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月20日(周二) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 无法拦截通过Direct System Call执行的进程注入行为 (Issue #34)




 
描述
 
开启增强防御后，使用https://bbs.kafan.cn/thread-2272539-1-1.html中的样本测试。确认样本执行成功，但iDefender无任何注入拦截提示。
 
系统环境
 
版本    Windows 10 专业版
 版本号    22H2
 安装日期    ‎2024/‎3/‎31
 操作系统内部版本    19045.4780
 体验    Windows Feature Experience Pack 1000.19060.1000.0
 
复现步骤
  
开启所有默认规则
 
开启增强防御
 
导入自制规则myrule.zip
 
在规则制定的文件夹下运行样本
  
预期结果
 
参考IDA逆向结果和云沙箱结果，该样本应该会通过Direct Syscall ZwCreateThreadEx函数，最终注入explorer.exe，但是iDefender在过程中并未提示拦截。

**Comment by Swizzzer** [comment]
开启了。

2024年8月20日 17:27，wecooperate ***@***.***> 写道：


开启默认都资源管理器防御了吗？
这个使用进程保护来拦截。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月20日(周二) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] 无法拦截通过Direct System Call执行的进程注入行为 (Issue #34)





描述

开启增强防御后，使用https://bbs.kafan.cn/thread-2272539-1-1.html中的样本测试。确认样本执行成功，但iDefender无任何注入拦截提示。

系统环境

版本 Windows 10 专业版
版本号 22H2
安装日期 ‎2024/‎3/‎31
操作系统内部版本 19045.4780
体验 Windows Feature Experience Pack 1000.19060.1000.0

复现步骤

开启所有默认规则

开启增强防御

导入自制规则myrule.zip

在规则制定的文件夹下运行样本

预期结果

参考IDA逆向结果和云沙箱结果，该样本应该会通过Direct Syscall ZwCreateThreadEx函数，最终注入explorer.exe，但是iDefender在过程中并未提示拦截。

**Comment by Swizzzer** [comment]
先确认一下， `资源管理器防御` 这项规则会记录日志吗？因为我判断iDefender无拦截的依据是无日志记录+记录到了Syscall操作，我现在想到如果规则本身不记录日志的话，这就不足以确证iDefender无法拦截。

**Comment by wecooperate** [comment]
内核防护都不会记录的，需要确认是否注入成功。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月20日(周二) 下午5:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 无法拦截通过Direct System Call执行的进程注入行为 (Issue #34)




 
先确认一下， 资源管理器防御 这项规则会记录日志吗？因为我判断iDefender无拦截的依据是无日志记录+记录到了Syscall操作，我现在想到如果规则本身不记录日志的话，这就不足以确证iDefender无法拦截。

**Comment by Swizzzer** [comment]
感谢告知。

顺便问一下，冰盾考虑加入对录音设备的保护吗？使用[Spyshelter antitest tool](https://wwa.lanzoui.com/i0rIfrl09wj)测试发现冰盾的"开启摄像头"规则不保护录音设备，规则模版中也没有找到对录音设备保护的选项。

**Comment by wecooperate** [comment]
录音等有时间了支持一下，之前有人可以通过拦截注册表来拦截。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月20日(周二) 晚上6:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 无法拦截通过Direct System Call执行的进程注入行为 (Issue #34)




 
感谢告知。
 
顺便问一下，冰盾考虑加入对录音设备的保护吗？使用Spyshelter antitest tool测试发现冰盾的"开启摄像头"规则不保护录音设备，规则模版中也没有找到对录音设备保护的选项。
