### ISSUE TITLE
"禁止修改文件"规则相关问题

### ISSUE THREAD

**Issue by HPflower** [wecooperate/iDefender#4]
最佳目标：希望java.exe进程在任何位置释放jar后缀文件时都弹窗拦截

实际：所有进程的文件释放行为都遭到拦截

不相关的建议：将主防弹窗中的“信任”修改为“放行”也许更适合？
![屏幕截图 2023-03-16 000621](https://user-images.githubusercontent.com/102914382/225373328-c9c8ec8a-8414-4ad0-b57b-5ded103602ff.png)
![屏幕截图 2023-03-16 000634](https://user-images.githubusercontent.com/102914382/225373337-174fcafb-3d59-4736-b944-9ebcae15f898.png)
![屏幕截图 2023-03-16 001351](https://user-images.githubusercontent.com/102914382/225373346-c3c0bab6-6c27-464f-a232-02b6d580ada3.png)

**Comment by wecooperate** [comment]
收到，下个版本添加对应的模板或者规则。
信任修改成放行（或者允许）。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日(周四) 凌晨0:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] "禁止修改文件"规则相关问题 (Issue #4)




 
最佳目标：希望java.exe进程在任何位置释放jar后缀文件时都弹窗拦截
 
实际：所有进程的文件释放行为都遭到拦截
 
不相关的建议：将主防弹窗中的“信任”修改为“放行”也许更适合？

**Comment by wecooperate** [comment]
看截图是使用了禁止修改文件的模板，可以换成禁止进程修改文件的模板，这个支持同时设置进程路径跟文件路径的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日(周四) 凌晨0:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wecooperate/iDefender] "禁止修改文件"规则相关问题 (Issue #4)




 
最佳目标：希望java.exe进程在任何位置释放jar后缀文件时都弹窗拦截
 
实际：所有进程的文件释放行为都遭到拦截
 
不相关的建议：将主防弹窗中的“信任”修改为“放行”也许更适合？

**Comment by HPflower** [comment]
感谢，相关问题已经解决

**Comment by wecooperate** [comment]
2.5.2 发布：将弹框的信任调整成允许；弹框（默认信任）调整成弹框（默认允许）
