### ISSUE TITLE
冰盾无法启动

### ISSUE THREAD

**Issue by HPflower** [wecooperate/iDefender#5]
冰盾无法正常进入界面
![屏幕截图 2023-04-06 204223](https://user-images.githubusercontent.com/102914382/230381831-0731daed-8c7e-47c1-aa7f-8b2a87e88547.png)

本地装载有卡巴斯基21.9，不知是否存在潜在的冲突

**Comment by wecooperate** [comment]
冰盾的版本是否最新，如果不是先更新到最新的版本？
如果最新了还出现，帮忙抓取一份dump（任务管理器 - iDefender进程右键 - 创建转储文件）

**Comment by HPflower** [comment]
本地冰盾版本为：2.5.3.0

系统版本为：
版本	Windows 11 企业版
版本	22H2
安装日期	‎2023/‎1/‎19
操作系统版本	22621.1485
体验	Windows Feature Experience Pack 1000.22639.1000.0


卡巴斯基版本：21.9.6.465


冰盾 · 主动防御系统以及相关服务的的dump：https://wwjw.lanzoum.com/iA9340sayezc

**Comment by wecooperate** [comment]
收到，我们分析一下原因



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月7日(周五) 中午12:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 冰盾无法启动 (Issue #5)




 
本地冰盾版本为：2.5.3.0
 
系统版本为：
 版本	Windows 11 企业版
 版本	22H2
 安装日期	‎2023/‎1/‎19
 操作系统版本	22621.1485
 体验	Windows Feature Experience Pack 1000.22639.1000.0
 
卡巴斯基版本：21.9.6.465
 
冰盾 · 主动防御系统以及相关服务的的dump：https://wwjw.lanzoum.com/iA9340sayezc

**Comment by wecooperate** [comment]
iDefender的dump文件大小是0，看能不能重新上传一份？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月7日(周五) 中午12:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wecooperate/iDefender] 冰盾无法启动 (Issue #5)




 
本地冰盾版本为：2.5.3.0
 
系统版本为：
 版本	Windows 11 企业版
 版本	22H2
 安装日期	‎2023/‎1/‎19
 操作系统版本	22621.1485
 体验	Windows Feature Experience Pack 1000.22639.1000.0
 
卡巴斯基版本：21.9.6.465
 
冰盾 · 主动防御系统以及相关服务的的dump：https://wwjw.lanzoum.com/iA9340sayezc

**Comment by wecooperate** [comment]
安装了卡巴斯基，可以重现冲突。
如果托盘启动了，可以从托盘直接启动界面，这个是正常的。
如果托盘没启动，双击启动的时候，进程会出现挂起状态（而且没有任何权限操作，没法抓dump，也没法恢复继续执行）使用ProcessHacker恢复挂起的线程（恢复挂起的进程不行）后，可以正常执行。
具体原因我再分析一下，看是哪里导致的冲突。

**Comment by wecooperate** [comment]
你那边是不是开启了自保护？目前看是跟冰盾的自保护有关，iDefender.exe启动的时候，卡巴斯基挂起了线程，但是被自保护了，没有权限打开线程恢复不了，导致进程一直处于挂起状态。
可以关闭自保护功能，或者临时退出卡巴斯基的avp.exe进程解决。
我再看看这个场景怎么优化一下，避免再出现。

**Comment by HPflower** [comment]
好的，感谢跟进

**Comment by wecooperate** [comment]
2.6.0 已经发布，请更新到新的版本
