### ISSUE TITLE
主程序崩溃

### ISSUE THREAD

**Issue by sanhu5** [wecooperate/iDefender#6]
随意添加了一段专家规则josn ，冰盾托盘进程直接崩溃，如何恢复。
卸载重装也一样闪退

**Comment by wecooperate** [comment]
应该是错误的参数导致模板渲染异常，下个版本修复。
解决可以删除 C:\ProgramData\iDefender 这个目录下面的配置 rules.dat rules.dat.bak （或者整个目录删除）

**Comment by sanhu5** [comment]
好的谢谢
