### ISSUE TITLE
询问弹窗时截图会卡机！

### ISSUE THREAD

**Issue by sanhu5** [wecooperate/iDefender#7]
弹窗的时候用FSCapture截图会卡几十秒。
可能是两个弹窗连一起，大约半分钟能动的时候是两个连一起弹出来的
![image](https://user-images.githubusercontent.com/59349735/230887022-9f1bae91-3d82-406b-a8b8-c9176fbf23bf.png)

**Comment by wecooperate** [comment]
弹框截图的时候，FSCapture打开又触发了弹框逻辑，多个弹框事件只会依次弹框，所以弹框没点击确认的时候，FSCapture会阻塞住，直到超时。超时了才会触发第二个弹框，同时界面存在倒计时（这个倒计时比真实超时短），一般弹框倒计时会先到达结束的。出现两个弹框的可能是界面被冻结了，导致服务超时了，但是界面一直没有动。
刚才下载FSCapture设置了相应的规则后没法重现，虽然FSCapture被拦截卡在后面了，但是弹框的倒计时还是正常的。

**Comment by sanhu5** [comment]
> 弹框截图的时候，FSCapture打开又触发了弹框逻辑，多个弹框事件只会依次弹框，所以弹框没点击确认的时候，FSCapture会阻塞住，直到超时。超时了才会触发第二个弹框，同时界面存在倒计时（这个倒计时比真实超时短），一般弹框倒计时会先到达结束的。出现两个弹框的可能是界面被冻结了，导致服务超时了，但是界面一直没有动。 刚才下载FSCapture设置了相应的规则后没法重现，虽然FSCapture被拦截卡在后面了，但是弹框的倒计时还是正常的。

把默认规则安全加固里面那个winlogon勾上，然后随便创建一个建立新进程的弹窗规则，试试能否重现。
虽然流程上没问题，但是实际现象界面电脑桌面像死机一样，任务操作都无法使用，鼠标也动不了，直到半分钟都才恢复。

**Comment by wecooperate** [comment]
嗯，我们想办法定位优化一下，正常系统不应该卡住的，最多只是截图进程卡。

**Comment by sanhu5** [comment]
> 嗯，我们想办法定位优化一下，正常系统不应该卡住的，最多只是截图进程卡。

也可能是我同时安装了火绒和冰盾的缘故

**Comment by wecooperate** [comment]
测试了各种注册表操作相关的，找到一个场景会导致整个界面卡住，但是不确定是否相同。
修改主题设置的时候（修改系统背景的注册表项），会导致所有界面都卡住，所有UI相关线程都阻塞了，弹框会弹不出来，出现类似上面卡死的场景。
对于这种UI线程被阻塞的场景，下个版本会加个优化，界面如果卡住了就不弹框了，直接执行默认策略返回，这样可以防止出现系统卡死的情况。
但是不确定上面这个场景是否是相同的，还是因为其他冲突导致相互等待。

**Comment by wecooperate** [comment]
2.6.0 发布已经修复，请更新到新的版本
