### ISSUE TITLE
进程和文件，能否支持父进程（发起程序）

### ISSUE THREAD

**Issue by sanhu5** [wecooperate/iDefender#9]
进程和文件，能否支持父进程（发起程序）。
目前所有类都只能编辑子进程（目标）。

**Comment by wecooperate** [comment]
2.6.0发布了，添加两个模板可以支持这种设置：
1. 拦截进程创建子进程模板
2. 快速模板（拦截模式）
请更新到最新的版本
![image](https://user-images.githubusercontent.com/63456933/231375954-4de7ecde-21b0-43b4-956b-5c008b26b88b.png)
![image](https://user-images.githubusercontent.com/63456933/231376054-399bca1e-a367-4072-84a0-5dc720ad1ac5.png)
